### ISSUE TITLE
deploy.sh:4-7: Continue implementing deploy scripts. Find...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#126]
The puzzle `45-954dc960` from #45 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/22c8326ead867e6e7ac59606acaabd1b2aa79986/deploy.sh#L4-L7

The puzzle was created by Boris Kuzmic on 03-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/126#issuecomment-461562882))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#126](https://github.com/timelesslounge/timelessis/issues/126), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#126](https://github.com/timelesslounge/timelessis/issues/126) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/644aa41f-e39e-47eb-8297-4bbfcd9fc09d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by bkuzmic** [comment]
@emilianodellacasa At this stage are we still going to use Digital Ocean Droplet or some other free solution?

**Comment by emilianodellacasa** [comment]
@bkuzmic the do droplet is already available

**Comment by bkuzmic** [comment]
@emilianodellacasa Please provide more info about how to connect to that droplet, like ip address and user. Can you import Rultor public key so we can login without password from Rultor machine?

**Comment by emilianodellacasa** [comment]
@bkuzmic of course, this is what I will do

**Comment by bkuzmic** [comment]
@0crat wait for architect to provide more information to finish the task.

**Comment by 0crat** [comment]
> @0crat wait for architect to provide more information to finish the task. ([here](https://github.com/timelesslounge/timelessis/issues/126#issuecomment-462083937))

@bkuzmic The impediment for [#126](https://github.com/timelesslounge/timelessis/issues/126) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by emilianodellacasa** [comment]
@bkuzmic See issue #213 and the updated README file

**Comment by bkuzmic** [comment]
@emilianodellacasa Thanks for the update. Are you going to use public-key authentication on staging and production servers? Because using passwords is not secure enough - and I have to use utility, like sshpass, in order to connect to the server.

**Comment by emilianodellacasa** [comment]
@bkuzmic Done, I added the keys in the same dir, see README file

**Comment by bkuzmic** [comment]
@emilianodellacasa I think maybe I didn't explain it well enough. We need to add the public key of Rultor user into the .ssh/authorized_keys on staging server (using ssh-copy-id is preferred). This is with assumption that staging server is fixed (not recreated always). Do you have the address of the staging server and user yet?

**Comment by emilianodellacasa** [comment]
@bkuzmic you were very clear, unfortunately it is not possible to do what you want. I asked Yegor and Kirill and it's the other way around: you create a key, upload the public to the server and add the private (encrypted) in rultor. If you look at rultor file in zerocracy repo is the way they do that

**Comment by bkuzmic** [comment]
@emilianodellacasa Oh, I see what you mean now. Now I can use:
`ssh -i staging.id_rsa staging_user@address `to login. 
Great, thanks for the help!

**Comment by 0pdd** [comment]
The puzzle `45-954dc960` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#126](https://github.com/timelesslounge/timelessis/issues/126) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#248](https://github.com/timelesslounge/timelessis/issues/248) are still not solved; solved: [#240](https://github.com/timelesslounge/timelessis/issues/240).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved; solved: [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved; solved: [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#299](https://github.com/timelesslounge/timelessis/issues/299) are still not solved; solved: [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#299](https://github.com/timelesslounge/timelessis/issues/299) is still not solved; solved: [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#374](https://github.com/timelesslounge/timelessis/issues/374) is still not solved; solved: [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#490](https://github.com/timelesslounge/timelessis/issues/490) is still not solved; solved: [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374).

**Comment by 0pdd** [comment]
@0pdd all 8 puzzles are solved here: [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374), [#490](https://github.com/timelesslounge/timelessis/issues/490).
