### ISSUE TITLE
views.py:18-20: Once UpdateView is implemented, refactor...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#311]
The puzzle `173-825cf970` from #173 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/43a0e0ec6d04b326ce0c63a8d143430b376aa6e6/timeless/views.py#L18-L20

The puzzle was created by Boris Kuzmic on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#311](https://github.com/timelesslounge/timelessis/issues/311) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#311](https://github.com/timelesslounge/timelessis/issues/311) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/857ed2cc-e3a9-4b42-a793-8a90343c4e57); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #438 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #438 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/311#issuecomment-468039794))

@paulodamaso The impediment for [#311](https://github.com/timelesslounge/timelessis/issues/311) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#442](https://github.com/timelesslounge/timelessis/issues/442), [#443](https://github.com/timelesslounge/timelessis/issues/443) are still not solved.

**Comment by paulodamaso** [comment]
@emilianodellacasa please take a look, 0pdd did not closed the ticket I've removed

**Comment by emilianodellacasa** [comment]
@paulodamaso I fear you mixed up issues: you removed another puzzle for issue #310 (that was already closed), and left this. So please submit another PR, removing the puzzle you wrongly updated and and modify the right one.

**Comment by paulodamaso** [comment]
@emilianodellacasa Sorry for the mess, I've fixed it now, please take a look

**Comment by 0pdd** [comment]
The puzzle `173-825cf970` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#442](https://github.com/timelesslounge/timelessis/issues/442), [#443](https://github.com/timelesslounge/timelessis/issues/443), [#475](https://github.com/timelesslounge/timelessis/issues/475) are still not solved.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#311](https://github.com/timelesslounge/timelessis/issues/311) is now out of scope

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/311#issuecomment-469719838))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#311](https://github.com/timelesslounge/timelessis/issues/311) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 11min
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23311%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/469/commits/040a173a75609880fc589d680909dbe7a6ed89e8) of your commits contains link to another issue. Please confirm you'll try to avoid this mistaked in future.

**Comment by paulodamaso** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#unknown](), [#unknown](), [#unknown]() are still not solved.
